// Native clean self-play: PUCT policy rows end at the first supported
// elementary certificate; physical completion then uses only the realizer.
#include "hex_puct/batched_inference_service.hpp"
#include "hex_puct/connection_certificate.hpp"
#include "hex_puct/connection_realizer.hpp"
#include "hex_puct/onnx_evaluator.hpp"
#include <atomic>
#include <chrono>
#include <filesystem>
#include <fstream>
#include <iostream>
#include <random>
#include <sstream>
#include <thread>
#include <unordered_map>
using namespace hex_puct; namespace fs=std::filesystem;
struct Prefix{std::string id;std::array<int,3> actions{};};
struct O{std::string model,out,run_id,model_sha,config_sha,stop_file,prefix_file,prefix_bank_sha;uint64_t seed=1,start=0;int games=1,budget=128,conc=1,batch=96,wait=200,watchdog=120;double cp=1.5,reduction=0.0;FpuMode fpu=FpuMode::Zero;bool v3=false;std::unordered_map<uint64_t,Prefix> prefixes;};
struct S{Color side;std::array<int,kBoardArea> visits;int move;int ply;};
static uint64_t Mix(uint64_t x){x+=0x9e3779b97f4a7c15ULL;x=(x^(x>>30))*0xbf58476d1ce4e5b9ULL;x=(x^(x>>27))*0x94d049bb133111ebULL;return x^(x>>31);}static uint64_t Seed(uint64_t b,uint64_t id){return Mix(b^Mix(id));}static char C(Color c){return c==Color::Black?'B':'W';}
static const char* FpuName(FpuMode m){return m==FpuMode::Zero?"zero":"parent_value_reduced";}
static int Pick(const std::array<int,kBoardArea>&v,std::mt19937_64&r,bool sample){if(!sample){int a=0;for(int i=1;i<kBoardArea;i++)if(v[i]>v[a])a=i;return a;}uint64_t n=0;for(int x:v)n+=x;uint64_t z=r()%n,a=0;for(int i=0;i<kBoardArea;i++){a+=v[i];if(z<a)return i;}throw std::runtime_error("visit sample");}
static bool Bridge(const ConnectionSegment&s){return s.kind==ConnectionSegmentKind::Bridge||s.kind==ConnectionSegmentKind::EdgeBridge;}
// Deterministic physical opponent for self-play Phase B. It attacks an
// unresolved carrier whenever possible; otherwise it maximises unresolved
// certificate distance. This is the same conservative adversarial policy
// used by the offline realizer qualification, not CNN/MCTS policy play.
static int Adversary(const Board& b,const ElementaryCertificateRealizer&r,const ConnectionCertificate& c){for(const auto&s:c.route)if(Bridge(s)&&b.LegalMask()[s.carriers[0]]&&b.LegalMask()[s.carriers[1]])return std::min(s.carriers[0],s.carriers[1]);int best=-1,n=-1;for(int a:b.LegalActions()){Board q=b;q.Play(a);auto p=r.Inspect(q);if(p.valid&&(p.unresolved_bridges>n||(p.unresolved_bridges==n&&a>best)))best=a,n=p.unresolved_bridges;}if(best>=0)return best;auto l=b.LegalActions();if(l.empty())throw std::runtime_error("no adversary move");return l.back();}
static void Arr(std::ostream&o,const std::array<int,kBoardArea>&x){o<<'[';for(int i=0;i<kBoardArea;i++){if(i)o<<',';o<<x[i];}o<<']';}static void Vec(std::ostream&o,const std::vector<int>&x){o<<'[';for(size_t i=0;i<x.size();i++){if(i)o<<',';o<<x[i];}o<<']';}
static void Cert(std::ostream&o,const ConnectionCertificate&c){o<<"{\"player\":\""<<C(c.player)<<"\",\"route\":[";for(size_t i=0;i<c.route.size();++i){if(i)o<<',';auto&s=c.route[i];o<<"{\"kind\":"<<int(s.kind)<<",\"endpoint_a\":"<<s.endpoint_a<<",\"endpoint_b\":"<<s.endpoint_b<<",\"carriers\":["<<s.carriers[0]<<','<<s.carriers[1]<<"]}";}o<<"]}";}
static O Parse(int n,char**v){O x;for(int i=1;i<n;i+=2){if(i+1>=n)throw std::runtime_error("missing value");std::string k=v[i],z=v[i+1];if(k=="--model")x.model=z;else if(k=="--output")x.out=z;else if(k=="--run-id")x.run_id=z;else if(k=="--model-sha")x.model_sha=z;else if(k=="--config-sha")x.config_sha=z;else if(k=="--master-seed")x.seed=std::stoull(z);else if(k=="--start-id")x.start=std::stoull(z);else if(k=="--games")x.games=std::stoi(z);else if(k=="--budget")x.budget=std::stoi(z);else if(k=="--concurrency")x.conc=std::stoi(z);else if(k=="--max-batch")x.batch=std::stoi(z);else if(k=="--wait-us")x.wait=std::stoi(z);else if(k=="--watchdog-seconds")x.watchdog=std::stoi(z);else if(k=="--stop-file")x.stop_file=z;else if(k=="--c-puct"){x.cp=std::stod(z);x.v3=true;}else if(k=="--fpu-mode"){if(z=="zero")x.fpu=FpuMode::Zero;else if(z=="parent_value_reduced")x.fpu=FpuMode::ParentValueReduced;else throw std::runtime_error("invalid fpu mode");x.v3=true;}else if(k=="--fpu-reduction"){x.reduction=std::stod(z);x.v3=true;}else if(k=="--prefix-assignments"){x.prefix_file=z;x.v3=true;}else if(k=="--prefix-bank-sha"){x.prefix_bank_sha=z;x.v3=true;}else throw std::runtime_error("unknown option "+k);}if(x.model.empty()||x.out.empty()||x.run_id.empty()||x.model_sha.empty()||x.config_sha.empty())throw std::runtime_error("required native-v2 option missing");if(x.budget<1||x.conc<1||x.batch<1||x.cp<0||x.reduction<0||(x.fpu==FpuMode::Zero&&x.reduction!=0))throw std::runtime_error("invalid native-v2 search options");return x;}
static void LoadPrefixes(O&x){if(x.prefix_file.empty())return;std::ifstream in(x.prefix_file);if(!in)throw std::runtime_error("cannot open prefix assignments");std::string line;while(std::getline(in,line)){if(line.empty())continue;std::stringstream q(line);std::string gid,id,actions;if(!std::getline(q,gid,'|')||!std::getline(q,id,'|')||!std::getline(q,actions))throw std::runtime_error("malformed prefix assignment");Prefix p;p.id=id;std::stringstream a(actions);std::string z;int i=0;while(std::getline(a,z,',')&&i<3)p.actions[i++]=std::stoi(z);if(i!=3||p.actions[0]<0||p.actions[0]>=kBoardArea||p.actions[1]<0||p.actions[1]>=kBoardArea||p.actions[2]<0||p.actions[2]>=kBoardArea||p.actions[0]==p.actions[1]||p.actions[0]==p.actions[2]||p.actions[1]==p.actions[2])throw std::runtime_error("invalid forced prefix");uint64_t game=std::stoull(gid);if(!x.prefixes.emplace(game,p).second)throw std::runtime_error("duplicate prefix assignment");}}
static void Quarantine(uint64_t id,const O&x,const std::string&reason){fs::path d=fs::path(x.out)/"quarantine";fs::create_directories(d);fs::path f=d/("game-"+std::to_string(id)+".json"),t=f.string()+".partial";std::ofstream o(t);o<<"{\"schema\":\""<<(x.v3?"hex-native-selfplay-game-v3":"hex-native-selfplay-game-v2")<<"\",\"status\":\"quarantined\",\"run_id\":\""<<x.run_id<<"\",\"game_id\":"<<id<<",\"game_seed\":"<<Seed(x.seed,id)<<",\"model_sha256\":\""<<x.model_sha<<"\",\"config_sha256\":\""<<x.config_sha<<"\",\"reason\":\""<<reason<<"\"}\n";o.close();fs::rename(t,f);}
static void Game(uint64_t id,const O&x,const Evaluator&e){Board b;std::mt19937_64 rng(Seed(x.seed,id));std::vector<int> moves,forced,phaseb;std::vector<std::string> phaseb_kind;std::vector<S> samples;std::optional<ConnectionCertificate> cert;int certply=0;Color owner=Color::Black;auto it=x.prefixes.find(id);if(it!=x.prefixes.end()){for(int a:it->second.actions){if(b.LiteralWinner()||!b.LegalMask()[a])throw std::runtime_error("illegal forced prefix move");b.Play(a);moves.push_back(a);forced.push_back(a);}}
 auto detect=[&](){auto bc=FindElementaryBridgeCertificate(b,Color::Black),wc=FindElementaryBridgeCertificate(b,Color::White);if(bc&&wc)throw std::runtime_error("simultaneous certificate");if(bc||wc){cert=bc?bc:wc;owner=cert->player;certply=int(moves.size());if(!ValidateElementaryBridgeCertificate(b,*cert)||owner!=(certply%2?Color::Black:Color::White))throw std::runtime_error("invalid/nonmoving certificate");}};if(!moves.empty())detect();SearchConfig search{x.budget,x.cp,x.fpu,x.reduction};
 while(!b.LiteralWinner()&&!cert){auto r=DeterministicPUCT(e,search).Search(b);if(!r.selected_action||r.root_visits!=x.budget)throw std::runtime_error("incomplete search");int a=Pick(r.raw_visits,rng,moves.size()<20);samples.push_back({b.side_to_move(),r.raw_visits,a,int(moves.size())});b.Play(a);moves.push_back(a);detect();}
 std::string classification="literal_before_certificate";if(cert){classification="certificate_realized";ElementaryCertificateRealizer realizer(b,*cert);while(!b.LiteralWinner()){int a;if(b.side_to_move()!=owner){a=Adversary(b,realizer,*cert);phaseb_kind.push_back("adversary");}else{auto d=realizer.ChooseMove(b,b.last_move());if(!d.action)throw std::runtime_error("realizer failure: "+d.reason);a=*d.action;phaseb_kind.push_back(d.kind==RealizerMoveKind::PairedResponse?"paired_response":"proactive_resolution");}if(!b.LegalMask()[a])throw std::runtime_error("phase-b illegal move");b.Play(a);moves.push_back(a);phaseb.push_back(a);}if(*b.LiteralWinner()!=owner)throw std::runtime_error("certificate/literal winner disagreement");}
 if(!b.LiteralWinner())throw std::runtime_error("no winner");fs::path final=fs::path(x.out)/"games"/("game-"+std::to_string(id)+".json");if(fs::exists(final))return;fs::path tmp=final.string()+".partial";std::ofstream o(tmp);o<<"{\"schema\":\""<<(x.v3?"hex-native-selfplay-game-v3":"hex-native-selfplay-game-v2")<<"\",\"status\":\"accepted\",\"run_id\":\""<<x.run_id<<"\",\"game_id\":"<<id<<",\"game_seed\":"<<Seed(x.seed,id)<<",\"seed_scheme\":\"splitmix64(master_seed XOR splitmix64(game_id))\",\"model_sha256\":\""<<x.model_sha<<"\",\"config_sha256\":\""<<x.config_sha<<"\",\"search_budget\":"<<x.budget<<",\"search_c_puct\":"<<x.cp<<",\"search_fpu_mode\":\""<<FpuName(x.fpu)<<"\",\"search_fpu_reduction\":"<<x.reduction<<",\"exploration\":{\"temperature_plies\":20,\"temperature\":1,\"after\":\"argmax\",\"dirichlet\":false},\"prefix_mode\":\""<<(it==x.prefixes.end()?"normal":"forced")<<"\",\"prefix_bank_sha256\":";if(it==x.prefixes.end())o<<"null";else o<<"\""<<x.prefix_bank_sha<<"\"";o<<",\"prefix_id\":";if(it==x.prefixes.end())o<<"null";else o<<"\""<<it->second.id<<"\"";o<<",\"forced_prefix_length\":"<<forced.size()<<",\"forced_prefix_actions\":[";for(size_t i=0;i<forced.size();++i){if(i)o<<',';o<<forced[i];}o<<"],\"moves\":";Vec(o,moves);o<<",\"phase_a_rows\":"<<samples.size()<<",\"certificate_ply\":";if(cert)o<<certply;else o<<"null";o<<",\"certificate_owner\":";if(cert)o<<"\""<<C(owner)<<"\"";else o<<"null";o<<",\"certificate\":";if(cert)Cert(o,*cert);else o<<"null";o<<",\"phase_b_moves\":[";for(size_t i=0;i<phaseb.size();++i){if(i)o<<',';o<<"{\"action\":"<<phaseb[i]<<",\"kind\":\""<<phaseb_kind[i]<<"\"}";}o<<"],\"literal_winner\":\""<<C(*b.LiteralWinner())<<"\",\"classification\":\""<<classification<<"\",\"samples\":[";for(size_t i=0;i<samples.size();i++){if(i)o<<',';auto&s=samples[i];o<<"{\"ply\":"<<s.ply<<",\"side_to_move\":\""<<C(s.side)<<"\",\"root_visits\":";Arr(o,s.visits);o<<",\"selected_move\":"<<s.move<<",\"z\":"<<(s.side==*b.LiteralWinner()?1:-1)<<'}';}o<<"]}\n";o.close();fs::rename(tmp,final);}
int main(int n,char**v){try{O x=Parse(n,v);LoadPrefixes(x);if(x.v3&&!x.prefix_file.empty()&&x.prefixes.size()!=size_t(x.games))throw std::runtime_error("prefix assignment count does not match game wave");fs::create_directories(fs::path(x.out)/"games");OnnxCudaBatchEvaluator model(x.model);SharedInferenceService service(model,{size_t(x.batch),256,std::chrono::microseconds(x.wait)});std::atomic<uint64_t>next{x.start};std::atomic<bool>stop=false,watch_stop=false;std::exception_ptr err;std::mutex mu;std::thread watchdog([&]{while(!watch_stop){std::this_thread::sleep_for(std::chrono::seconds(1));auto h=service.Health();if(h.failed){stop=true;return;}if(h.outstanding_requests&&h.seconds_since_last_success>x.watchdog){service.Fail(std::make_exception_ptr(std::runtime_error("native selfplay inference watchdog timeout")));stop=true;return;}}});auto w=[&]{try{while(!stop){if(!x.stop_file.empty()&&fs::exists(x.stop_file)){stop=true;break;}auto id=next++;if(id>=x.start+uint64_t(x.games))break;try{Game(id,x,EncodedBoardEvaluator(service));}catch(const std::exception&e){if(service.Health().failed)throw;Quarantine(id,x,e.what());}}}catch(...){std::lock_guard l(mu);err=std::current_exception();stop=true;}};std::vector<std::thread>ts;for(int i=0;i<x.conc;i++)ts.emplace_back(w);for(auto&t:ts)t.join();watch_stop=true;watchdog.join();service.Shutdown();if(err)std::rethrow_exception(err);auto s=service.Stats();std::cout<<"{\"status\":\"complete\",\"requests\":"<<s.requests<<",\"batches\":"<<s.batches<<"}\n";return 0;}catch(const std::exception&e){std::cerr<<"native selfplay error: "<<e.what()<<'\n';return 1;}}
